[main]
plainMatcher=org.apache.shiro.authc.credential.SimpleCredentialsMatcher
iniRealm.credentialsMatcher = $plainMatcher
localhostFilter=org.apache.jena.fuseki.authz.LocalhostFilter

[users]
TS_USER_PLACEHOLDER = TS_PASS_PLACEHOLDER, admin

[roles]
admin = *

;[urls]
;/$/ping = anon
;/** = authcBasic

[urls]
/$/ping = anon
/$/server = anon
/$/** = authcBasic,user[admin]
/**  = authcBasic,user[admin]