---
config:
  flowchart:
    curve: linear
    htmlLabels: true
    useMaxWidth: true
  look: handDrawn
  theme: base
  themeVariables:
    fontFamily: '''Architects Daughter'', cursive'
    fontSize: 20px
    lineColor: '#FFAB91'
    primaryBorderColor: '#143642'
    primaryColor: '#FFF3E0'
    primaryTextColor: '#372237'
---
graph TD;
	__start__([<p>__start__</p>]):::first
	Convert\20to\20Markdown(Convert to Markdown)
	Chunk\20Text(Chunk Text)
	Update\20Ontology(Update Ontology)
	Normalize\20Ontology\20Updates(Normalize Ontology Updates)
	Consolidate\20Ontology(Consolidate Ontology)
	Render\20Facts(Render Facts)
	Merge\20Facts(Merge Facts)
	Structural\20Check(Structural Check)
	Consistency\20Critic(Consistency Critic)
	Serialize(Serialize)
	__end__([<p>__end__</p>]):::last
	Chunk\20Text -.-> Render\20Facts;
	Chunk\20Text -.-> Update\20Ontology;
	Consistency\20Critic -.-> Render\20Facts;
	Consistency\20Critic -.-> Serialize;
	Consolidate\20Ontology --> Structural\20Check;
	Convert\20to\20Markdown --> Chunk\20Text;
	Merge\20Facts --> Serialize;
	Normalize\20Ontology\20Updates --> Consolidate\20Ontology;
	Render\20Facts --> Merge\20Facts;
	Structural\20Check --> Consistency\20Critic;
	Update\20Ontology --> Normalize\20Ontology\20Updates;
	__start__ --> Convert\20to\20Markdown;
	Serialize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
